# Generated by Django 4.1.7 on 2023-04-01 00:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.CharField(default='USUARIO', max_length=32)),
                ('nroCelular', models.CharField(default='999888777', max_length=32)),
                ('profesionUsuario', models.CharField(default='DEVELOPER', max_length=32)),
                ('perfilUsuario', models.CharField(default='', max_length=512)),
                ('fechaIngreso', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
