# Generated by Django 4.2 on 2023-04-20 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_tareas', '0002_tareasinformacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarioTarea', models.CharField(default='', max_length=512)),
                ('tareaRelacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_tareas.tareasinformacion')),
                ('usuarioRelacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
